### PR TITLE
[Types] Fixing types again, removing unnecessary Tokens, fixes #12

### LINKED ISSUE #12: DOT Token needed
@ymherklotz In one of the past commits, you deleted `DOT`, however `NUMBER DOT SPACE(>=1)` form an ordered list
```
1. 5
2.    4
5. 44
6.5
```

1. 5
2.    4
5. 44
6.5

### PR DESCRIPTION
**Pull request by ymherklotz**

### CODE REVIEW

File: FMark/Types.fs [hunk 1]
```diff
@@ -8,14 +8,11 @@ type Language =
...
 type Token =
     | CODEBLOCK of string * Language
-    | LITERAL of string
-    | EMPHASIS of string
-    | STRONG of string
-    | INLINECODE of string
+    | LITERAL
     | WHITESPACE of size: int
-    | NUMBER of int
+    | NUMBER of string
```
Comment (ThunderMikey) [inline FMark/Types.fs]: Would `6.5` be one `NUMBER` or `NUMBER DOT NUMBER`? Is this way you change from `int` to `string`?

File: FMark/Types.fs [hunk 2]
```diff
@@ -8,14 +8,11 @@ type Language =
 
 type Token =
     | CODEBLOCK of string * Language
-    | LITERAL of string
-    | EMPHASIS of string
-    | STRONG of string
-    | INLINECODE of string
+    | LITERAL
```
Comment (ThunderMikey) [inline FMark/Types.fs]: `LITERAL of string`?
